In [ ]:
## Goal

The goal of this notebook is to build the datasets used in this project:

- FIFA rankings dataset (from API)
- World Cup titles dataset (manually created)
- Historical match results (from Kaggle)

These datasets are later used for analysis and simulation.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import os
from dotenv import load_dotenv

load_dotenv()
api_key = os.getenv("FIFA_API")

headers = {
    'Authorization': f'Bearer {api_key}'
}

In [ ]:
## FIFA Rankings Data (API)

We use the Zyla Labs FIFA API to retrieve the most recent FIFA rankings.
This includes team name, rank, and points.

Steps:
1. Request available ranking dates
2. Select the most recent dataset
3. Extract relevant fields (rank, team name, points)

In [2]:
import requests

# The endpoint URL for Ranking by Date
url = "https://zylalabs.com/api/3028/fifa+ranking+api/3199/historical+ranking"

# Replace 'YOUR_API_KEY' with your actual Zyla Labs access key
headers = {
    'Authorization': f'{api_key}'
}


try:
    response = requests.get(url, headers=headers)
    
    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()
        print(data)
        
        # Loop through the first few rankings
    else:
        print(f"Error: {response.status_code} - {response.text}")

except Exception as e:
    print(f"An error occurred: {e}")

[{'id': 'FRS_Male_Football_20260119', 'date': '01 April 2026'}, {'id': 'FRS_Male_Football_20251219', 'date': '19 January 2026'}, {'id': 'FRS_Male_Football_20251119', 'date': '23 December 2025'}, {'id': 'FRS_Male_Football_20251015', 'date': '19 November 2025'}, {'id': 'FRS_Male_Football_20250910', 'date': '17 October 2025'}, {'id': 'id14870', 'date': '18 September 2025'}, {'id': 'id14800', 'date': '10 July 2025'}, {'id': 'id14702', 'date': '03 April 2025'}, {'id': 'id14597', 'date': '19 December 2024'}, {'id': 'id14576', 'date': '28 November 2024'}, {'id': 'id14541', 'date': '24 October 2024'}, {'id': 'id14506', 'date': '19 September 2024'}, {'id': 'id14443', 'date': '18 July 2024'}, {'id': 'id14415', 'date': '20 June 2024'}, {'id': 'id14338', 'date': '04 April 2024'}, {'id': 'id14289', 'date': '15 February 2024'}, {'id': 'id14233', 'date': '21 December 2023'}, {'id': 'id14212', 'date': '30 November 2023'}, {'id': 'id14177', 'date': '26 October 2023'}, {'id': 'id14142', 'date': '21 September 2023'}, {'id': 'id14079', 'date': '20 July 2023'}, {'id': 'id14058', 'date': '29 June 2023'}, {'id': 'id13974', 'date': '06 April 2023'}, {'id': 'id13869', 'date': '22 December 2022'}, {'id': 'id13792', 'date': '06 October 2022'}, {'id': 'id13750', 'date': '25 August 2022'}, {'id': 'id13687', 'date': '23 June 2022'}, {'id': 'id13603', 'date': '31 March 2022'}, {'id': 'id13554', 'date': '10 February 2022'}, {'id': 'id13505', 'date': '23 December 2021'}, {'id': 'id13471', 'date': '19 November 2021'}, {'id': 'id13442', 'date': '21 October 2021'}, {'id': 'id13407', 'date': '16 September 2021'}, {'id': 'id13372', 'date': '12 August 2021'}, {'id': 'id13295', 'date': '27 May 2021'}, {'id': 'id13245', 'date': '07 April 2021'}, {'id': 'id13197', 'date': '18 February 2021'}, {'id': 'id13127', 'date': '10 December 2020'}, {'id': 'id13113', 'date': '26 November 2020'}, {'id': 'id13078', 'date': '22 October 2020'}, {'id': 'id13043', 'date': '17 September 2020'}, {'id': 'id12884', 'date': '16 July 2020'}, {'id': 'id12883', 'date': '11 June 2020'}, {'id': 'id12882', 'date': '09 April 2020'}, {'id': 'id12833', 'date': '20 February 2020'}, {'id': 'id12770', 'date': '19 December 2019'}, {'id': 'id12749', 'date': '28 November 2019'}, {'id': 'id12714', 'date': '24 October 2019'}, {'id': 'id12679', 'date': '19 September 2019'}, {'id': 'id12623', 'date': '25 July 2019'}, {'id': 'id12582', 'date': '14 June 2019'}, {'id': 'id12511', 'date': '04 April 2019'}, {'id': 'id12455', 'date': '07 February 2019'}, {'id': 'id12406', 'date': '20 December 2018'}, {'id': 'id12385', 'date': '29 November 2018'}, {'id': 'id12350', 'date': '25 October 2018'}, {'id': 'id12315', 'date': '20 September 2018'}, {'id': 'id12280', 'date': '16 August 2018'}, {'id': 'id12252', 'date': '01 July 2018'}, {'id': 'id12210', 'date': '07 June 2018'}, {'id': 'id12189', 'date': '17 May 2018'}, {'id': 'id12154', 'date': '12 April 2018'}, {'id': 'id12126', 'date': '15 March 2018'}, {'id': 'id12098', 'date': '15 February 2018'}, {'id': 'id12070', 'date': '18 January 2018'}, {'id': 'id12042', 'date': '21 December 2017'}, {'id': 'id12014', 'date': '23 November 2017'}, {'id': 'id11976', 'date': '16 October 2017'}, {'id': 'id11944', 'date': '14 September 2017'}, {'id': 'id11909', 'date': '10 August 2017'}, {'id': 'id11874', 'date': '06 July 2017'}, {'id': 'id11839', 'date': '01 June 2017'}, {'id': 'id11811', 'date': '04 May 2017'}, {'id': 'id11783', 'date': '06 April 2017'}, {'id': 'id11755', 'date': '09 March 2017'}, {'id': 'id11727', 'date': '09 February 2017'}, {'id': 'id11699', 'date': '12 January 2017'}, {'id': 'id11678', 'date': '22 December 2016'}, {'id': 'id11650', 'date': '24 November 2016'}, {'id': 'id11615', 'date': '20 October 2016'}, {'id': 'id11580', 'date': '15 September 2016'}, {'id': 'id11545', 'date': '11 August 2016'}, {'id': 'id11517', 'date': '14 July 2016'}, {'id': 'id11475', 'date': '02 June 2016'}, {'id': 'id11447', 'date': '05 May 2016'}, {'id': 'id11419', 'date': '07 April 2016'}, {'id': 'id11384', 'date': '03 March 2016'}, {'id': 'id11356', 'date': '04 February 2016'}, {'id': 'id11328', 'date': '07 January 2016'}, {'id': 'id11293', 'date': '03 December 2015'}, {'id': 'id11265', 'date': '05 November 2015'}, {'id': 'id11230', 'date': '01 October 2015'}, {'id': 'id11202', 'date': '03 September 2015'}, {'id': 'id11174', 'date': '06 August 2015'}, {'id': 'id11146', 'date': '09 July 2015'}, {'id': 'id11111', 'date': '04 June 2015'}, {'id': 'id11083', 'date': '07 May 2015'}, {'id': 'id11055', 'date': '09 April 2015'}, {'id': 'id11027', 'date': '12 March 2015'}, {'id': 'id10999', 'date': '12 February 2015'}, {'id': 'id10964', 'date': '08 January 2015'}, {'id': 'id10943', 'date': '18 December 2014'}, {'id': 'id10922', 'date': '27 November 2014'}, {'id': 'id10887', 'date': '23 October 2014'}, {'id': 'id10852', 'date': '18 September 2014'}, {'id': 'id10817', 'date': '14 August 2014'}, {'id': 'id10789', 'date': '17 July 2014'}, {'id': 'id10747', 'date': '05 June 2014'}, {'id': 'id10719', 'date': '08 May 2014'}, {'id': 'id10691', 'date': '10 April 2014'}, {'id': 'id10663', 'date': '13 March 2014'}, {'id': 'id10635', 'date': '13 February 2014'}, {'id': 'id10607', 'date': '16 January 2014'}, {'id': 'id10579', 'date': '19 December 2013'}, {'id': 'id10558', 'date': '28 November 2013'}, {'id': 'id10516', 'date': '17 October 2013'}, {'id': 'id10481', 'date': '12 September 2013'}, {'id': 'id10446', 'date': '08 August 2013'}, {'id': 'id10411', 'date': '04 July 2013'}, {'id': 'id10383', 'date': '06 June 2013'}, {'id': 'id10355', 'date': '09 May 2013'}, {'id': 'id10327', 'date': '11 April 2013'}, {'id': 'id10299', 'date': '14 March 2013'}, {'id': 'id10271', 'date': '14 February 2013'}, {'id': 'id10243', 'date': '17 January 2013'}, {'id': 'id10214', 'date': '19 December 2012'}, {'id': 'id10172', 'date': '07 November 2012'}, {'id': 'id10137', 'date': '03 October 2012'}, {'id': 'id10109', 'date': '05 September 2012'}, {'id': 'id10081', 'date': '08 August 2012'}, {'id': 'id10046', 'date': '04 July 2012'}, {'id': 'id10018', 'date': '06 June 2012'}, {'id': 'id9990', 'date': '09 May 2012'}, {'id': 'id9962', 'date': '11 April 2012'}, {'id': 'id9927', 'date': '07 March 2012'}, {'id': 'id9906', 'date': '15 February 2012'}, {'id': 'id9878', 'date': '18 January 2012'}, {'id': 'id9850', 'date': '21 December 2011'}, {'id': 'id9822', 'date': '23 November 2011'}, {'id': 'id9787', 'date': '19 October 2011'}, {'id': 'id9759', 'date': '21 September 2011'}, {'id': 'id9731', 'date': '24 August 2011'}, {'id': 'id9703', 'date': '27 July 2011'}, {'id': 'id9675', 'date': '29 June 2011'}, {'id': 'id9633', 'date': '18 May 2011'}, {'id': 'id9598', 'date': '13 April 2011'}, {'id': 'id9563', 'date': '09 March 2011'}, {'id': 'id9528', 'date': '02 February 2011'}, {'id': 'id9507', 'date': '12 January 2011'}, {'id': 'id9479', 'date': '15 December 2010'}, {'id': 'id9451', 'date': '17 November 2010'}, {'id': 'id9423', 'date': '20 October 2010'}, {'id': 'id9388', 'date': '15 September 2010'}, {'id': 'id9353', 'date': '11 August 2010'}, {'id': 'id9325', 'date': '14 July 2010'}, {'id': 'id9276', 'date': '26 May 2010'}, {'id': 'id9248', 'date': '28 April 2010'}, {'id': 'id9220', 'date': '31 March 2010'}, {'id': 'id9192', 'date': '03 March 2010'}, {'id': 'id9164', 'date': '03 February 2010'}, {'id': 'id9115', 'date': '16 December 2009'}, {'id': 'id9089', 'date': '20 November 2009'}, {'id': 'id9054', 'date': '16 October 2009'}, {'id': 'id9010', 'date': '02 September 2009'}, {'id': 'id8982', 'date': '05 August 2009'}, {'id': 'id8947', 'date': '01 July 2009'}, {'id': 'id8919', 'date': '03 June 2009'}, {'id': 'id8891', 'date': '06 May 2009'}, {'id': 'id8863', 'date': '08 April 2009'}, {'id': 'id8835', 'date': '11 March 2009'}, {'id': 'id8807', 'date': '11 February 2009'}, {'id': 'id8779', 'date': '14 January 2009'}, {'id': 'id8751', 'date': '17 December 2008'}, {'id': 'id8716', 'date': '12 November 2008'}, {'id': 'id8681', 'date': '08 October 2008'}, {'id': 'id8646', 'date': '03 September 2008'}, {'id': 'id8618', 'date': '06 August 2008'}, {'id': 'id8583', 'date': '02 July 2008'}, {'id': 'id8555', 'date': '04 June 2008'}, {'id': 'id8527', 'date': '07 May 2008'}, {'id': 'id8499', 'date': '09 April 2008'}, {'id': 'id8471', 'date': '12 March 2008'}, {'id': 'id8443', 'date': '13 February 2008'}, {'id': 'id8415', 'date': '16 January 2008'}, {'id': 'id8385', 'date': '17 December 2007'}, {'id': 'id8360', 'date': '22 November 2007'}, {'id': 'id8331', 'date': '24 October 2007'}, {'id': 'id8296', 'date': '19 September 2007'}, {'id': 'id8268', 'date': '22 August 2007'}, {'id': 'id8233', 'date': '18 July 2007'}, {'id': 'id8198', 'date': '13 June 2007'}, {'id': 'id8170', 'date': '16 May 2007'}, {'id': 'id8142', 'date': '18 April 2007'}, {'id': 'id8107', 'date': '14 March 2007'}, {'id': 'id8079', 'date': '14 February 2007'}, {'id': 'id152', 'date': '17 January 2007'}, {'id': 'id151', 'date': '18 December 2006'}, {'id': 'id150', 'date': '22 November 2006'}, {'id': 'id149', 'date': '18 October 2006'}, {'id': 'id148', 'date': '13 September 2006'}, {'id': 'id147', 'date': '16 August 2006'}, {'id': 'id146', 'date': '12 July 2006'}, {'id': 'id145', 'date': '17 May 2006'}, {'id': 'id144', 'date': '19 April 2006'}, {'id': 'id143', 'date': '15 March 2006'}, {'id': 'id142', 'date': '15 February 2006'}, {'id': 'id141', 'date': '18 January 2006'}, {'id': 'id140', 'date': '16 December 2005'}, {'id': 'id139', 'date': '21 November 2005'}, {'id': 'id138', 'date': '17 October 2005'}, {'id': 'id137', 'date': '12 September 2005'}, {'id': 'id136', 'date': '17 August 2005'}, {'id': 'id135', 'date': '20 July 2005'}, {'id': 'id134', 'date': '15 June 2005'}, {'id': 'id133', 'date': '18 May 2005'}, {'id': 'id132', 'date': '20 April 2005'}, {'id': 'id131', 'date': '23 March 2005'}, {'id': 'id130', 'date': '16 February 2005'}, {'id': 'id129', 'date': '19 January 2005'}, {'id': 'id128', 'date': '20 December 2004'}, {'id': 'id127', 'date': '10 November 2004'}, {'id': 'id126', 'date': '06 October 2004'}, {'id': 'id125', 'date': '01 September 2004'}, {'id': 'id124', 'date': '04 August 2004'}, {'id': 'id123', 'date': '07 July 2004'}, {'id': 'id122', 'date': '09 June 2004'}, {'id': 'id121', 'date': '12 May 2004'}, {'id': 'id120', 'date': '14 April 2004'}, {'id': 'id119', 'date': '17 March 2004'}, {'id': 'id118', 'date': '18 February 2004'}, {'id': 'id117', 'date': '14 January 2004'}, {'id': 'id116', 'date': '15 December 2003'}, {'id': 'id115', 'date': '19 November 2003'}, {'id': 'id114', 'date': '22 October 2003'}, {'id': 'id113', 'date': '24 September 2003'}, {'id': 'id112', 'date': '27 August 2003'}, {'id': 'id111', 'date': '30 July 2003'}, {'id': 'id110', 'date': '25 June 2003'}, {'id': 'id109', 'date': '21 May 2003'}, {'id': 'id108', 'date': '23 April 2003'}, {'id': 'id107', 'date': '26 March 2003'}, {'id': 'id106', 'date': '19 February 2003'}, {'id': 'id105', 'date': '15 January 2003'}, {'id': 'id103', 'date': '18 December 2002'}, {'id': 'id102', 'date': '20 November 2002'}, {'id': 'id101', 'date': '23 October 2002'}, {'id': 'id100', 'date': '18 September 2002'}, {'id': 'id99', 'date': '14 August 2002'}, {'id': 'id98', 'date': '03 July 2002'}, {'id': 'id97', 'date': '15 May 2002'}, {'id': 'id96', 'date': '17 April 2002'}, {'id': 'id95', 'date': '20 March 2002'}, {'id': 'id94', 'date': '13 February 2002'}, {'id': 'id93', 'date': '16 January 2002'}, {'id': 'id92', 'date': '19 December 2001'}, {'id': 'id91', 'date': '21 November 2001'}, {'id': 'id90', 'date': '17 October 2001'}, {'id': 'id89', 'date': '19 September 2001'}, {'id': 'id88', 'date': '22 August 2001'}, {'id': 'id87', 'date': '18 July 2001'}, {'id': 'id86', 'date': '20 June 2001'}, {'id': 'id85', 'date': '16 May 2001'}, {'id': 'id84', 'date': '11 April 2001'}, {'id': 'id83', 'date': '14 March 2001'}, {'id': 'id82', 'date': '14 February 2001'}, {'id': 'id81', 'date': '17 January 2001'}, {'id': 'id80', 'date': '20 December 2000'}, {'id': 'id79', 'date': '15 November 2000'}, {'id': 'id78', 'date': '11 October 2000'}, {'id': 'id77', 'date': '06 September 2000'}, {'id': 'id76', 'date': '09 August 2000'}, {'id': 'id75', 'date': '05 July 2000'}, {'id': 'id74', 'date': '07 June 2000'}, {'id': 'id73', 'date': '10 May 2000'}, {'id': 'id72', 'date': '12 April 2000'}, {'id': 'id71', 'date': '15 March 2000'}, {'id': 'id70', 'date': '16 February 2000'}, {'id': 'id69', 'date': '19 January 2000'}, {'id': 'id68', 'date': '22 December 1999'}, {'id': 'id67', 'date': '17 November 1999'}, {'id': 'id66', 'date': '13 October 1999'}, {'id': 'id65', 'date': '15 September 1999'}, {'id': 'id64', 'date': '18 August 1999'}, {'id': 'id63', 'date': '21 July 1999'}, {'id': 'id62', 'date': '16 June 1999'}, {'id': 'id61', 'date': '19 May 1999'}, {'id': 'id60', 'date': '21 April 1999'}, {'id': 'id59', 'date': '24 March 1999'}, {'id': 'id58', 'date': '24 February 1999'}, {'id': 'id57', 'date': '27 January 1999'}, {'id': 'id56', 'date': '23 December 1998'}, {'id': 'id55', 'date': '18 November 1998'}, {'id': 'id54', 'date': '21 October 1998'}, {'id': 'id53', 'date': '16 September 1998'}, {'id': 'id52', 'date': '19 August 1998'}, {'id': 'id51', 'date': '15 July 1998'}, {'id': 'id50', 'date': '20 May 1998'}, {'id': 'id49', 'date': '22 April 1998'}, {'id': 'id48', 'date': '18 March 1998'}, {'id': 'id47', 'date': '18 February 1998'}, {'id': 'id46', 'date': '23 December 1997'}, {'id': 'id45', 'date': '19 November 1997'}, {'id': 'id44', 'date': '17 October 1997'}, {'id': 'id43', 'date': '17 September 1997'}, {'id': 'id42', 'date': '20 August 1997'}, {'id': 'id41', 'date': '16 July 1997'}, {'id': 'id40', 'date': '18 June 1997'}, {'id': 'id39', 'date': '14 May 1997'}, {'id': 'id38', 'date': '09 April 1997'}, {'id': 'id37', 'date': '27 February 1997'}, {'id': 'id36', 'date': '18 December 1996'}, {'id': 'id35', 'date': '20 November 1996'}, {'id': 'id34', 'date': '23 October 1996'}, {'id': 'id33', 'date': '25 September 1996'}, {'id': 'id32', 'date': '28 August 1996'}, {'id': 'id31', 'date': '03 July 1996'}, {'id': 'id30', 'date': '22 May 1996'}, {'id': 'id29', 'date': '24 April 1996'}, {'id': 'id28', 'date': '21 February 1996'}, {'id': 'id27', 'date': '24 January 1996'}, {'id': 'id26', 'date': '19 December 1995'}, {'id': 'id25', 'date': '21 November 1995'}, {'id': 'id24', 'date': '17 October 1995'}, {'id': 'id23', 'date': '19 September 1995'}, {'id': 'id22', 'date': '22 August 1995'}, {'id': 'id21', 'date': '25 July 1995'}, {'id': 'id20', 'date': '13 June 1995'}, {'id': 'id19', 'date': '16 May 1995'}, {'id': 'id18', 'date': '19 April 1995'}, {'id': 'id17', 'date': '20 February 1995'}, {'id': 'id16', 'date': '20 December 1994'}, {'id': 'id15', 'date': '22 November 1994'}, {'id': 'id14', 'date': '25 October 1994'}, {'id': 'id13', 'date': '13 September 1994'}, {'id': 'id12', 'date': '21 July 1994'}, {'id': 'id11', 'date': '14 June 1994'}, {'id': 'id10', 'date': '17 May 1994'}, {'id': 'id9', 'date': '19 April 1994'}, {'id': 'id8', 'date': '15 March 1994'}, {'id': 'id7', 'date': '15 February 1994'}, {'id': 'id6', 'date': '23 December 1993'}, {'id': 'id5', 'date': '19 November 1993'}, {'id': 'id4', 'date': '22 October 1993'}, {'id': 'id3', 'date': '23 September 1993'}, {'id': 'id2', 'date': '08 August 1993'}, {'id': 'id1', 'date': '31 December 1992'}]

In [3]:
import requests

url = "https://zylalabs.com/api/3028/fifa+ranking+api/3200/ranking+by+date"

# Use the full string including the numbers and the pipe symbol
headers = {
    'Authorization': f'{api_key}'
}

params = {
    'id': 'id14870'
}

response = requests.get(url, headers=headers, params=params)

if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print(f"Failed: {response.status_code}")

{'date': '18 September, 2025', 'ranking': [{'rank': 1, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ESP', 'name': 'Spain', 'previous_rank': 2, 'points': 1875.37, 'previous_points': 1867.09, 'confederation': 'UEFA'}, {'rank': 2, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/FRA', 'name': 'France', 'previous_rank': 3, 'points': 1870.92, 'previous_points': 1862.03, 'confederation': 'UEFA'}, {'rank': 3, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ARG', 'name': 'Argentina', 'previous_rank': 1, 'points': 1870.32, 'previous_points': 1885.36, 'confederation': 'CONMEBOL'}, {'rank': 4, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ENG', 'name': 'England', 'previous_rank': 4, 'points': 1820.44, 'previous_points': 1813.32, 'confederation': 'UEFA'}, {'rank': 5, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/POR', 'name': 'Portugal', 'previous_rank': 6, 'points': 1779.55, 'previous_points': 1770.53, 'confederation': 'UEFA'}, {'rank': 6, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BRA', 'name': 'Brazil', 'previous_rank': 5, 'points': 1761.6, 'previous_points': 1777.69, 'confederation': 'CONMEBOL'}, {'rank': 7, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/NED', 'name': 'Netherlands', 'previous_rank': 7, 'points': 1754.17, 'previous_points': 1758.18, 'confederation': 'UEFA'}, {'rank': 8, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BEL', 'name': 'Belgium', 'previous_rank': 8, 'points': 1739.54, 'previous_points': 1736.38, 'confederation': 'UEFA'}, {'rank': 9, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CRO', 'name': 'Croatia', 'previous_rank': 10, 'points': 1714.2, 'previous_points': 1707.51, 'confederation': 'UEFA'}, {'rank': 10, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ITA', 'name': 'Italy', 'previous_rank': 11, 'points': 1710.06, 'previous_points': 1702.58, 'confederation': 'UEFA'}, {'rank': 11, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MAR', 'name': 'Morocco', 'previous_rank': 12, 'points': 1706.27, 'previous_points': 1698.72, 'confederation': 'CAF'}, {'rank': 12, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GER', 'name': 'Germany', 'previous_rank': 9, 'points': 1704.27, 'previous_points': 1716.98, 'confederation': 'UEFA'}, {'rank': 13, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/COL', 'name': 'Colombia', 'previous_rank': 14, 'points': 1692.1, 'previous_points': 1679.46, 'confederation': 'CONMEBOL'}, {'rank': 14, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MEX', 'name': 'Mexico', 'previous_rank': 13, 'points': 1688.38, 'previous_points': 1689.73, 'confederation': 'CONCACAF'}, {'rank': 15, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/URU', 'name': 'Uruguay', 'previous_rank': 16, 'points': 1673.65, 'previous_points': 1670.76, 'confederation': 'CONMEBOL'}, {'rank': 16, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/USA', 'name': 'USA', 'previous_rank': 15, 'points': 1670.04, 'previous_points': 1671.04, 'confederation': 'CONCACAF'}, {'rank': 17, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SUI', 'name': 'Switzerland', 'previous_rank': 19, 'points': 1648.3, 'previous_points': 1635.08, 'confederation': 'UEFA'}, {'rank': 18, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SEN', 'name': 'Senegal', 'previous_rank': 18, 'points': 1645.23, 'previous_points': 1635.1, 'confederation': 'CAF'}, {'rank': 19, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/JPN', 'name': 'Japan', 'previous_rank': 17, 'points': 1640.47, 'previous_points': 1641.23, 'confederation': 'AFC'}, {'rank': 20, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/DEN', 'name': 'Denmark', 'previous_rank': 21, 'points': 1627.64, 'previous_points': 1621.24, 'confederation': 'UEFA'}, {'rank': 21, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/IRN', 'name': 'IR Iran', 'previous_rank': 20, 'points': 1622.61, 'previous_points': 1624.3, 'confederation': 'AFC'}, {'rank': 22, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/AUT', 'name': 'Austria', 'previous_rank': 22, 'points': 1601.86, 'previous_points': 1591.24, 'confederation': 'UEFA'}, {'rank': 23, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/KOR', 'name': 'Korea Republic', 'previous_rank': 23, 'points': 1593.19, 'previous_points': 1587.08, 'confederation': 'AFC'}, {'rank': 24, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ECU', 'name': 'Ecuador', 'previous_rank': 25, 'points': 1588.04, 'previous_points': 1570.68, 'confederation': 'CONMEBOL'}, {'rank': 25, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/AUS', 'name': 'Australia', 'previous_rank': 24, 'points': 1583.49, 'previous_points': 1578.57, 'confederation': 'AFC'}, {'rank': 26, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CAN', 'name': 'Canada', 'previous_rank': 28, 'points': 1558.04, 'previous_points': 1548.94, 'confederation': 'CONCACAF'}, {'rank': 27, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/TUR', 'name': 'Türkiye', 'previous_rank': 27, 'points': 1555.72, 'previous_points': 1553.19, 'confederation': 'UEFA'}, {'rank': 28, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/UKR', 'name': 'Ukraine', 'previous_rank': 26, 'points': 1543.06, 'previous_points': 1557.21, 'confederation': 'UEFA'}, {'rank': 29, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/PAN', 'name': 'Panama', 'previous_rank': 30, 'points': 1529.71, 'previous_points': 1545.08, 'confederation': 'CONCACAF'}, {'rank': 30, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/WAL', 'name': 'Wales', 'previous_rank': 31, 'points': 1529.09, 'previous_points': 1528.93, 'confederation': 'UEFA'}, {'rank': 31, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/NOR', 'name': 'Norway', 'previous_rank': 33, 'points': 1526.23, 'previous_points': 1519.42, 'confederation': 'UEFA'}, {'rank': 32, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SWE', 'name': 'Sweden', 'previous_rank': 29, 'points': 1524.62, 'previous_points': 1545.43, 'confederation': 'UEFA'}, {'rank': 33, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/RUS', 'name': 'Russia', 'previous_rank': 35, 'points': 1521.74, 'previous_points': 1518.54, 'confederation': 'UEFA'}, {'rank': 34, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SRB', 'name': 'Serbia', 'previous_rank': 32, 'points': 1520.9, 'previous_points': 1523.03, 'confederation': 'UEFA'}, {'rank': 35, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/EGY', 'name': 'Egypt', 'previous_rank': 34, 'points': 1519.18, 'previous_points': 1518.79, 'confederation': 'CAF'}, {'rank': 36, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/POL', 'name': 'Poland', 'previous_rank': 37, 'points': 1517.3, 'previous_points': 1502.4, 'confederation': 'UEFA'}, {'rank': 37, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/PAR', 'name': 'Paraguay', 'previous_rank': 43, 'points': 1501.01, 'previous_points': 1486.69, 'confederation': 'CONMEBOL'}, {'rank': 38, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ALG', 'name': 'Algeria', 'previous_rank': 36, 'points': 1500.74, 'previous_points': 1503.8, 'confederation': 'CAF'}, {'rank': 39, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CZE', 'name': 'Czechia', 'previous_rank': 41, 'points': 1500.29, 'previous_points': 1492.4, 'confederation': 'UEFA'}, {'rank': 40, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GRE', 'name': 'Greece', 'previous_rank': 39, 'points': 1494.72, 'previous_points': 1497.82, 'confederation': 'UEFA'}, {'rank': 41, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/HUN', 'name': 'Hungary', 'previous_rank': 38, 'points': 1492.18, 'previous_points': 1500.74, 'confederation': 'UEFA'}, {'rank': 42, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SVK', 'name': 'Slovakia', 'previous_rank': 52, 'points': 1491.87, 'previous_points': 1466.56, 'confederation': 'UEFA'}, {'rank': 43, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SCO', 'name': 'Scotland', 'previous_rank': 47, 'points': 1485.08, 'previous_points': 1474.68, 'confederation': 'UEFA'}, {'rank': 44, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CIV', 'name': "Côte d'Ivoire", 'previous_rank': 45, 'points': 1483.9, 'previous_points': 1483.45, 'confederation': 'CAF'}, {'rank': 45, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/NGA', 'name': 'Nigeria', 'previous_rank': 44, 'points': 1483.86, 'previous_points': 1484.26, 'confederation': 'CAF'}, {'rank': 46, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/TUN', 'name': 'Tunisia', 'previous_rank': 49, 'points': 1483.02, 'previous_points': 1471.1, 'confederation': 'CAF'}, {'rank': 47, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CRC', 'name': 'Costa Rica', 'previous_rank': 40, 'points': 1481.13, 'previous_points': 1493.85, 'confederation': 'CONCACAF'}, {'rank': 48, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/PER', 'name': 'Peru', 'previous_rank': 42, 'points': 1469.31, 'previous_points': 1489.97, 'confederation': 'CONMEBOL'}, {'rank': 49, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/VEN', 'name': 'Venezuela', 'previous_rank': 46, 'points': 1465.02, 'previous_points': 1477.02, 'confederation': 'CONMEBOL'}, {'rank': 50, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SVN', 'name': 'Slovenia', 'previous_rank': 50, 'points': 1462.96, 'previous_points': 1469.76, 'confederation': 'UEFA'}, {'rank': 51, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ROU', 'name': 'Romania', 'previous_rank': 48, 'points': 1462.85, 'previous_points': 1474.46, 'confederation': 'UEFA'}, {'rank': 52, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CMR', 'name': 'Cameroon', 'previous_rank': 51, 'points': 1455.42, 'previous_points': 1466.97, 'confederation': 'CAF'}, {'rank': 53, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/QAT', 'name': 'Qatar', 'previous_rank': 53, 'points': 1453.65, 'previous_points': 1459.85, 'confederation': 'AFC'}, {'rank': 54, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/UZB', 'name': 'Uzbekistan', 'previous_rank': 55, 'points': 1453.31, 'previous_points': 1449.12, 'confederation': 'AFC'}, {'rank': 55, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/RSA', 'name': 'South Africa', 'previous_rank': 56, 'points': 1448.67, 'previous_points': 1443.31, 'confederation': 'CAF'}, {'rank': 56, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MLI', 'name': 'Mali', 'previous_rank': 54, 'points': 1445.83, 'previous_points': 1454.72, 'confederation': 'CAF'}, {'rank': 57, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CHI', 'name': 'Chile', 'previous_rank': 57, 'points': 1441.66, 'previous_points': 1441.62, 'confederation': 'CONMEBOL'}, {'rank': 58, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/IRQ', 'name': 'Iraq', 'previous_rank': 58, 'points': 1422.2, 'previous_points': 1417.04, 'confederation': 'AFC'}, {'rank': 59, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/KSA', 'name': 'Saudi Arabia', 'previous_rank': 59, 'points': 1420.65, 'previous_points': 1415.11, 'confederation': 'AFC'}, {'rank': 60, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/COD', 'name': 'Congo DR', 'previous_rank': 61, 'points': 1407.6, 'previous_points': 1412.1, 'confederation': 'CAF'}, {'rank': 61, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/IRL', 'name': 'Republic of Ireland', 'previous_rank': 60, 'points': 1397.52, 'previous_points': 1412.76, 'confederation': 'UEFA'}, {'rank': 62, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/JOR', 'name': 'Jordan', 'previous_rank': 64, 'points': 1391.33, 'previous_points': 1387.79, 'confederation': 'AFC'}, {'rank': 63, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MKD', 'name': 'North Macedonia', 'previous_rank': 62, 'points': 1388.5, 'previous_points': 1390.79, 'confederation': 'UEFA'}, {'rank': 64, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BFA', 'name': 'Burkina Faso', 'previous_rank': 63, 'points': 1385.37, 'previous_points': 1388.03, 'confederation': 'CAF'}, {'rank': 65, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/HON', 'name': 'Honduras', 'previous_rank': 66, 'points': 1383.98, 'previous_points': 1379.84, 'confederation': 'CONCACAF'}, {'rank': 66, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ALB', 'name': 'Albania', 'previous_rank': 68, 'points': 1380.66, 'previous_points': 1373.15, 'confederation': 'UEFA'}, {'rank': 67, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/UAE', 'name': 'United Arab Emirates', 'previous_rank': 65, 'points': 1379.86, 'previous_points': 1379.86, 'confederation': 'AFC'}, {'rank': 68, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GEO', 'name': 'Georgia', 'previous_rank': 67, 'points': 1377.32, 'previous_points': 1375.23, 'confederation': 'UEFA'}, {'rank': 69, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/JAM', 'name': 'Jamaica', 'previous_rank': 70, 'points': 1377.22, 'previous_points': 1362.97, 'confederation': 'CONCACAF'}, {'rank': 70, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CPV', 'name': 'Cabo Verde', 'previous_rank': 73, 'points': 1363.21, 'previous_points': 1343.68, 'confederation': 'CAF'}, {'rank': 71, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/FIN', 'name': 'Finland', 'previous_rank': 69, 'points': 1358.72, 'previous_points': 1371.55, 'confederation': 'UEFA'}, {'rank': 72, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/NIR', 'name': 'Northern Ireland', 'previous_rank': 71, 'points': 1355.98, 'previous_points': 1351.01, 'confederation': 'UEFA'}, {'rank': 73, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BIH', 'name': 'Bosnia and Herzegovina', 'previous_rank': 72, 'points': 1344.25, 'previous_points': 1349.11, 'confederation': 'UEFA'}, {'rank': 74, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ISL', 'name': 'Iceland', 'previous_rank': 74, 'points': 1343.09, 'previous_points': 1337.92, 'confederation': 'UEFA'}, {'rank': 75, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GHA', 'name': 'Ghana', 'previous_rank': 76, 'points': 1340.84, 'previous_points': 1333.33, 'confederation': 'CAF'}, {'rank': 76, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ISR', 'name': 'Israel', 'previous_rank': 75, 'points': 1337.4, 'previous_points': 1336.52, 'confederation': 'UEFA'}, {'rank': 77, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BOL', 'name': 'Bolivia', 'previous_rank': 78, 'points': 1332.24, 'previous_points': 1315.71, 'confederation': 'CONMEBOL'}, {'rank': 78, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/OMA', 'name': 'Oman', 'previous_rank': 79, 'points': 1320.34, 'previous_points': 1314.41, 'confederation': 'AFC'}, {'rank': 79, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GAB', 'name': 'Gabon', 'previous_rank': 80, 'points': 1314.06, 'previous_points': 1306.6, 'confederation': 'CAF'}, {'rank': 80, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MNE', 'name': 'Montenegro', 'previous_rank': 77, 'points': 1314.05, 'previous_points': 1327.28, 'confederation': 'UEFA'}, {'rank': 81, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GUI', 'name': 'Guinea', 'previous_rank': 81, 'points': 1299.49, 'previous_points': 1292.63, 'confederation': 'CAF'}, {'rank': 82, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/UGA', 'name': 'Uganda', 'previous_rank': 88, 'points': 1287.61, 'previous_points': 1269.37, 'confederation': 'CAF'}, {'rank': 83, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/NZL', 'name': 'New Zealand', 'previous_rank': 82, 'points': 1283.94, 'previous_points': 1288.86, 'confederation': 'OFC'}, {'rank': 84, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CUW', 'name': 'Curaçao', 'previous_rank': 86, 'points': 1282.42, 'previous_points': 1277.22, 'confederation': 'CONCACAF'}, {'rank': 85, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ZAM', 'name': 'Zambia', 'previous_rank': 83, 'points': 1273, 'previous_points': 1285.32, 'confederation': 'CAF'}, {'rank': 86, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BUL', 'name': 'Bulgaria', 'previous_rank': 84, 'points': 1271.52, 'previous_points': 1284.42, 'confederation': 'UEFA'}, {'rank': 87, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/HAI', 'name': 'Haiti', 'previous_rank': 90, 'points': 1269.24, 'previous_points': 1261.42, 'confederation': 'CONCACAF'}, {'rank': 88, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BHR', 'name': 'Bahrain', 'previous_rank': 89, 'points': 1268.73, 'previous_points': 1266.96, 'confederation': 'AFC'}, {'rank': 89, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ANG', 'name': 'Angola', 'previous_rank': 85, 'points': 1268.72, 'previous_points': 1279.55, 'confederation': 'CAF'}, {'rank': 90, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SLV', 'name': 'El Salvador', 'previous_rank': 87, 'points': 1267.75, 'previous_points': 1272.7, 'confederation': 'CONCACAF'}, {'rank': 91, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/KOS', 'name': 'Kosovo', 'previous_rank': 95, 'points': 1262.1, 'previous_points': 1247.71, 'confederation': 'UEFA'}, {'rank': 92, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SYR', 'name': 'Syria', 'previous_rank': 91, 'points': 1259.32, 'previous_points': 1260.82, 'confederation': 'AFC'}, {'rank': 93, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BEN', 'name': 'Benin', 'previous_rank': 96, 'points': 1257.3, 'previous_points': 1238.97, 'confederation': 'CAF'}, {'rank': 94, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CHN', 'name': 'China PR', 'previous_rank': 94, 'points': 1249.06, 'previous_points': 1249.46, 'confederation': 'AFC'}, {'rank': 95, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/EQG', 'name': 'Equatorial Guinea', 'previous_rank': 93, 'points': 1248.68, 'previous_points': 1251.59, 'confederation': 'CAF'}, {'rank': 96, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/LUX', 'name': 'Luxembourg', 'previous_rank': 92, 'points': 1242.61, 'previous_points': 1260.17, 'confederation': 'UEFA'}, {'rank': 97, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MOZ', 'name': 'Mozambique', 'previous_rank': 99, 'points': 1234.04, 'previous_points': 1236.18, 'confederation': 'CAF'}, {'rank': 98, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GUA', 'name': 'Guatemala', 'previous_rank': 100, 'points': 1230.73, 'previous_points': 1235.63, 'confederation': 'CONCACAF'}, {'rank': 99, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/PLE', 'name': 'Palestine', 'previous_rank': 98, 'points': 1230.55, 'previous_points': 1236.44, 'confederation': 'AFC'}, {'rank': 100, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BLR', 'name': 'Belarus', 'previous_rank': 97, 'points': 1223.54, 'previous_points': 1237.24, 'confederation': 'UEFA'}, {'rank': 101, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/THA', 'name': 'Thailand', 'previous_rank': 102, 'points': 1222.2, 'previous_points': 1222.07, 'confederation': 'AFC'}, {'rank': 102, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/TRI', 'name': 'Trinidad and Tobago', 'previous_rank': 101, 'points': 1220.99, 'previous_points': 1229.11, 'confederation': 'CONCACAF'}, {'rank': 103, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ARM', 'name': 'Armenia', 'previous_rank': 105, 'points': 1219.55, 'previous_points': 1204.78, 'confederation': 'UEFA'}, {'rank': 104, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/TJK', 'name': 'Tajikistan', 'previous_rank': 106, 'points': 1206.15, 'previous_points': 1202.54, 'confederation': 'AFC'}, {'rank': 105, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/COM', 'name': 'Comoros', 'previous_rank': 107, 'points': 1201.83, 'previous_points': 1198.51, 'confederation': 'CAF'}, {'rank': 106, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/KGZ', 'name': 'Kyrgyz Re

In [4]:
raw_list = data.get('ranking',[])
print(raw_list)
df = pd.DataFrame(raw_list)

[{'rank': 1, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ESP', 'name': 'Spain', 'previous_rank': 2, 'points': 1875.37, 'previous_points': 1867.09, 'confederation': 'UEFA'}, {'rank': 2, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/FRA', 'name': 'France', 'previous_rank': 3, 'points': 1870.92, 'previous_points': 1862.03, 'confederation': 'UEFA'}, {'rank': 3, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ARG', 'name': 'Argentina', 'previous_rank': 1, 'points': 1870.32, 'previous_points': 1885.36, 'confederation': 'CONMEBOL'}, {'rank': 4, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ENG', 'name': 'England', 'previous_rank': 4, 'points': 1820.44, 'previous_points': 1813.32, 'confederation': 'UEFA'}, {'rank': 5, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/POR', 'name': 'Portugal', 'previous_rank': 6, 'points': 1779.55, 'previous_points': 1770.53, 'confederation': 'UEFA'}, {'rank': 6, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BRA', 'name': 'Brazil', 'previous_rank': 5, 'points': 1761.6, 'previous_points': 1777.69, 'confederation': 'CONMEBOL'}, {'rank': 7, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/NED', 'name': 'Netherlands', 'previous_rank': 7, 'points': 1754.17, 'previous_points': 1758.18, 'confederation': 'UEFA'}, {'rank': 8, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BEL', 'name': 'Belgium', 'previous_rank': 8, 'points': 1739.54, 'previous_points': 1736.38, 'confederation': 'UEFA'}, {'rank': 9, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CRO', 'name': 'Croatia', 'previous_rank': 10, 'points': 1714.2, 'previous_points': 1707.51, 'confederation': 'UEFA'}, {'rank': 10, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ITA', 'name': 'Italy', 'previous_rank': 11, 'points': 1710.06, 'previous_points': 1702.58, 'confederation': 'UEFA'}, {'rank': 11, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MAR', 'name': 'Morocco', 'previous_rank': 12, 'points': 1706.27, 'previous_points': 1698.72, 'confederation': 'CAF'}, {'rank': 12, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GER', 'name': 'Germany', 'previous_rank': 9, 'points': 1704.27, 'previous_points': 1716.98, 'confederation': 'UEFA'}, {'rank': 13, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/COL', 'name': 'Colombia', 'previous_rank': 14, 'points': 1692.1, 'previous_points': 1679.46, 'confederation': 'CONMEBOL'}, {'rank': 14, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MEX', 'name': 'Mexico', 'previous_rank': 13, 'points': 1688.38, 'previous_points': 1689.73, 'confederation': 'CONCACAF'}, {'rank': 15, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/URU', 'name': 'Uruguay', 'previous_rank': 16, 'points': 1673.65, 'previous_points': 1670.76, 'confederation': 'CONMEBOL'}, {'rank': 16, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/USA', 'name': 'USA', 'previous_rank': 15, 'points': 1670.04, 'previous_points': 1671.04, 'confederation': 'CONCACAF'}, {'rank': 17, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SUI', 'name': 'Switzerland', 'previous_rank': 19, 'points': 1648.3, 'previous_points': 1635.08, 'confederation': 'UEFA'}, {'rank': 18, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SEN', 'name': 'Senegal', 'previous_rank': 18, 'points': 1645.23, 'previous_points': 1635.1, 'confederation': 'CAF'}, {'rank': 19, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/JPN', 'name': 'Japan', 'previous_rank': 17, 'points': 1640.47, 'previous_points': 1641.23, 'confederation': 'AFC'}, {'rank': 20, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/DEN', 'name': 'Denmark', 'previous_rank': 21, 'points': 1627.64, 'previous_points': 1621.24, 'confederation': 'UEFA'}, {'rank': 21, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/IRN', 'name': 'IR Iran', 'previous_rank': 20, 'points': 1622.61, 'previous_points': 1624.3, 'confederation': 'AFC'}, {'rank': 22, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/AUT', 'name': 'Austria', 'previous_rank': 22, 'points': 1601.86, 'previous_points': 1591.24, 'confederation': 'UEFA'}, {'rank': 23, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/KOR', 'name': 'Korea Republic', 'previous_rank': 23, 'points': 1593.19, 'previous_points': 1587.08, 'confederation': 'AFC'}, {'rank': 24, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ECU', 'name': 'Ecuador', 'previous_rank': 25, 'points': 1588.04, 'previous_points': 1570.68, 'confederation': 'CONMEBOL'}, {'rank': 25, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/AUS', 'name': 'Australia', 'previous_rank': 24, 'points': 1583.49, 'previous_points': 1578.57, 'confederation': 'AFC'}, {'rank': 26, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CAN', 'name': 'Canada', 'previous_rank': 28, 'points': 1558.04, 'previous_points': 1548.94, 'confederation': 'CONCACAF'}, {'rank': 27, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/TUR', 'name': 'Türkiye', 'previous_rank': 27, 'points': 1555.72, 'previous_points': 1553.19, 'confederation': 'UEFA'}, {'rank': 28, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/UKR', 'name': 'Ukraine', 'previous_rank': 26, 'points': 1543.06, 'previous_points': 1557.21, 'confederation': 'UEFA'}, {'rank': 29, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/PAN', 'name': 'Panama', 'previous_rank': 30, 'points': 1529.71, 'previous_points': 1545.08, 'confederation': 'CONCACAF'}, {'rank': 30, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/WAL', 'name': 'Wales', 'previous_rank': 31, 'points': 1529.09, 'previous_points': 1528.93, 'confederation': 'UEFA'}, {'rank': 31, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/NOR', 'name': 'Norway', 'previous_rank': 33, 'points': 1526.23, 'previous_points': 1519.42, 'confederation': 'UEFA'}, {'rank': 32, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SWE', 'name': 'Sweden', 'previous_rank': 29, 'points': 1524.62, 'previous_points': 1545.43, 'confederation': 'UEFA'}, {'rank': 33, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/RUS', 'name': 'Russia', 'previous_rank': 35, 'points': 1521.74, 'previous_points': 1518.54, 'confederation': 'UEFA'}, {'rank': 34, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SRB', 'name': 'Serbia', 'previous_rank': 32, 'points': 1520.9, 'previous_points': 1523.03, 'confederation': 'UEFA'}, {'rank': 35, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/EGY', 'name': 'Egypt', 'previous_rank': 34, 'points': 1519.18, 'previous_points': 1518.79, 'confederation': 'CAF'}, {'rank': 36, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/POL', 'name': 'Poland', 'previous_rank': 37, 'points': 1517.3, 'previous_points': 1502.4, 'confederation': 'UEFA'}, {'rank': 37, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/PAR', 'name': 'Paraguay', 'previous_rank': 43, 'points': 1501.01, 'previous_points': 1486.69, 'confederation': 'CONMEBOL'}, {'rank': 38, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ALG', 'name': 'Algeria', 'previous_rank': 36, 'points': 1500.74, 'previous_points': 1503.8, 'confederation': 'CAF'}, {'rank': 39, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CZE', 'name': 'Czechia', 'previous_rank': 41, 'points': 1500.29, 'previous_points': 1492.4, 'confederation': 'UEFA'}, {'rank': 40, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GRE', 'name': 'Greece', 'previous_rank': 39, 'points': 1494.72, 'previous_points': 1497.82, 'confederation': 'UEFA'}, {'rank': 41, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/HUN', 'name': 'Hungary', 'previous_rank': 38, 'points': 1492.18, 'previous_points': 1500.74, 'confederation': 'UEFA'}, {'rank': 42, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SVK', 'name': 'Slovakia', 'previous_rank': 52, 'points': 1491.87, 'previous_points': 1466.56, 'confederation': 'UEFA'}, {'rank': 43, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SCO', 'name': 'Scotland', 'previous_rank': 47, 'points': 1485.08, 'previous_points': 1474.68, 'confederation': 'UEFA'}, {'rank': 44, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CIV', 'name': "Côte d'Ivoire", 'previous_rank': 45, 'points': 1483.9, 'previous_points': 1483.45, 'confederation': 'CAF'}, {'rank': 45, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/NGA', 'name': 'Nigeria', 'previous_rank': 44, 'points': 1483.86, 'previous_points': 1484.26, 'confederation': 'CAF'}, {'rank': 46, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/TUN', 'name': 'Tunisia', 'previous_rank': 49, 'points': 1483.02, 'previous_points': 1471.1, 'confederation': 'CAF'}, {'rank': 47, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CRC', 'name': 'Costa Rica', 'previous_rank': 40, 'points': 1481.13, 'previous_points': 1493.85, 'confederation': 'CONCACAF'}, {'rank': 48, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/PER', 'name': 'Peru', 'previous_rank': 42, 'points': 1469.31, 'previous_points': 1489.97, 'confederation': 'CONMEBOL'}, {'rank': 49, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/VEN', 'name': 'Venezuela', 'previous_rank': 46, 'points': 1465.02, 'previous_points': 1477.02, 'confederation': 'CONMEBOL'}, {'rank': 50, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SVN', 'name': 'Slovenia', 'previous_rank': 50, 'points': 1462.96, 'previous_points': 1469.76, 'confederation': 'UEFA'}, {'rank': 51, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ROU', 'name': 'Romania', 'previous_rank': 48, 'points': 1462.85, 'previous_points': 1474.46, 'confederation': 'UEFA'}, {'rank': 52, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CMR', 'name': 'Cameroon', 'previous_rank': 51, 'points': 1455.42, 'previous_points': 1466.97, 'confederation': 'CAF'}, {'rank': 53, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/QAT', 'name': 'Qatar', 'previous_rank': 53, 'points': 1453.65, 'previous_points': 1459.85, 'confederation': 'AFC'}, {'rank': 54, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/UZB', 'name': 'Uzbekistan', 'previous_rank': 55, 'points': 1453.31, 'previous_points': 1449.12, 'confederation': 'AFC'}, {'rank': 55, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/RSA', 'name': 'South Africa', 'previous_rank': 56, 'points': 1448.67, 'previous_points': 1443.31, 'confederation': 'CAF'}, {'rank': 56, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MLI', 'name': 'Mali', 'previous_rank': 54, 'points': 1445.83, 'previous_points': 1454.72, 'confederation': 'CAF'}, {'rank': 57, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CHI', 'name': 'Chile', 'previous_rank': 57, 'points': 1441.66, 'previous_points': 1441.62, 'confederation': 'CONMEBOL'}, {'rank': 58, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/IRQ', 'name': 'Iraq', 'previous_rank': 58, 'points': 1422.2, 'previous_points': 1417.04, 'confederation': 'AFC'}, {'rank': 59, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/KSA', 'name': 'Saudi Arabia', 'previous_rank': 59, 'points': 1420.65, 'previous_points': 1415.11, 'confederation': 'AFC'}, {'rank': 60, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/COD', 'name': 'Congo DR', 'previous_rank': 61, 'points': 1407.6, 'previous_points': 1412.1, 'confederation': 'CAF'}, {'rank': 61, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/IRL', 'name': 'Republic of Ireland', 'previous_rank': 60, 'points': 1397.52, 'previous_points': 1412.76, 'confederation': 'UEFA'}, {'rank': 62, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/JOR', 'name': 'Jordan', 'previous_rank': 64, 'points': 1391.33, 'previous_points': 1387.79, 'confederation': 'AFC'}, {'rank': 63, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MKD', 'name': 'North Macedonia', 'previous_rank': 62, 'points': 1388.5, 'previous_points': 1390.79, 'confederation': 'UEFA'}, {'rank': 64, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BFA', 'name': 'Burkina Faso', 'previous_rank': 63, 'points': 1385.37, 'previous_points': 1388.03, 'confederation': 'CAF'}, {'rank': 65, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/HON', 'name': 'Honduras', 'previous_rank': 66, 'points': 1383.98, 'previous_points': 1379.84, 'confederation': 'CONCACAF'}, {'rank': 66, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ALB', 'name': 'Albania', 'previous_rank': 68, 'points': 1380.66, 'previous_points': 1373.15, 'confederation': 'UEFA'}, {'rank': 67, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/UAE', 'name': 'United Arab Emirates', 'previous_rank': 65, 'points': 1379.86, 'previous_points': 1379.86, 'confederation': 'AFC'}, {'rank': 68, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GEO', 'name': 'Georgia', 'previous_rank': 67, 'points': 1377.32, 'previous_points': 1375.23, 'confederation': 'UEFA'}, {'rank': 69, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/JAM', 'name': 'Jamaica', 'previous_rank': 70, 'points': 1377.22, 'previous_points': 1362.97, 'confederation': 'CONCACAF'}, {'rank': 70, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CPV', 'name': 'Cabo Verde', 'previous_rank': 73, 'points': 1363.21, 'previous_points': 1343.68, 'confederation': 'CAF'}, {'rank': 71, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/FIN', 'name': 'Finland', 'previous_rank': 69, 'points': 1358.72, 'previous_points': 1371.55, 'confederation': 'UEFA'}, {'rank': 72, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/NIR', 'name': 'Northern Ireland', 'previous_rank': 71, 'points': 1355.98, 'previous_points': 1351.01, 'confederation': 'UEFA'}, {'rank': 73, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BIH', 'name': 'Bosnia and Herzegovina', 'previous_rank': 72, 'points': 1344.25, 'previous_points': 1349.11, 'confederation': 'UEFA'}, {'rank': 74, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ISL', 'name': 'Iceland', 'previous_rank': 74, 'points': 1343.09, 'previous_points': 1337.92, 'confederation': 'UEFA'}, {'rank': 75, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GHA', 'name': 'Ghana', 'previous_rank': 76, 'points': 1340.84, 'previous_points': 1333.33, 'confederation': 'CAF'}, {'rank': 76, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ISR', 'name': 'Israel', 'previous_rank': 75, 'points': 1337.4, 'previous_points': 1336.52, 'confederation': 'UEFA'}, {'rank': 77, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BOL', 'name': 'Bolivia', 'previous_rank': 78, 'points': 1332.24, 'previous_points': 1315.71, 'confederation': 'CONMEBOL'}, {'rank': 78, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/OMA', 'name': 'Oman', 'previous_rank': 79, 'points': 1320.34, 'previous_points': 1314.41, 'confederation': 'AFC'}, {'rank': 79, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GAB', 'name': 'Gabon', 'previous_rank': 80, 'points': 1314.06, 'previous_points': 1306.6, 'confederation': 'CAF'}, {'rank': 80, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MNE', 'name': 'Montenegro', 'previous_rank': 77, 'points': 1314.05, 'previous_points': 1327.28, 'confederation': 'UEFA'}, {'rank': 81, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GUI', 'name': 'Guinea', 'previous_rank': 81, 'points': 1299.49, 'previous_points': 1292.63, 'confederation': 'CAF'}, {'rank': 82, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/UGA', 'name': 'Uganda', 'previous_rank': 88, 'points': 1287.61, 'previous_points': 1269.37, 'confederation': 'CAF'}, {'rank': 83, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/NZL', 'name': 'New Zealand', 'previous_rank': 82, 'points': 1283.94, 'previous_points': 1288.86, 'confederation': 'OFC'}, {'rank': 84, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CUW', 'name': 'Curaçao', 'previous_rank': 86, 'points': 1282.42, 'previous_points': 1277.22, 'confederation': 'CONCACAF'}, {'rank': 85, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ZAM', 'name': 'Zambia', 'previous_rank': 83, 'points': 1273, 'previous_points': 1285.32, 'confederation': 'CAF'}, {'rank': 86, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BUL', 'name': 'Bulgaria', 'previous_rank': 84, 'points': 1271.52, 'previous_points': 1284.42, 'confederation': 'UEFA'}, {'rank': 87, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/HAI', 'name': 'Haiti', 'previous_rank': 90, 'points': 1269.24, 'previous_points': 1261.42, 'confederation': 'CONCACAF'}, {'rank': 88, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BHR', 'name': 'Bahrain', 'previous_rank': 89, 'points': 1268.73, 'previous_points': 1266.96, 'confederation': 'AFC'}, {'rank': 89, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ANG', 'name': 'Angola', 'previous_rank': 85, 'points': 1268.72, 'previous_points': 1279.55, 'confederation': 'CAF'}, {'rank': 90, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SLV', 'name': 'El Salvador', 'previous_rank': 87, 'points': 1267.75, 'previous_points': 1272.7, 'confederation': 'CONCACAF'}, {'rank': 91, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/KOS', 'name': 'Kosovo', 'previous_rank': 95, 'points': 1262.1, 'previous_points': 1247.71, 'confederation': 'UEFA'}, {'rank': 92, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/SYR', 'name': 'Syria', 'previous_rank': 91, 'points': 1259.32, 'previous_points': 1260.82, 'confederation': 'AFC'}, {'rank': 93, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BEN', 'name': 'Benin', 'previous_rank': 96, 'points': 1257.3, 'previous_points': 1238.97, 'confederation': 'CAF'}, {'rank': 94, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/CHN', 'name': 'China PR', 'previous_rank': 94, 'points': 1249.06, 'previous_points': 1249.46, 'confederation': 'AFC'}, {'rank': 95, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/EQG', 'name': 'Equatorial Guinea', 'previous_rank': 93, 'points': 1248.68, 'previous_points': 1251.59, 'confederation': 'CAF'}, {'rank': 96, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/LUX', 'name': 'Luxembourg', 'previous_rank': 92, 'points': 1242.61, 'previous_points': 1260.17, 'confederation': 'UEFA'}, {'rank': 97, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/MOZ', 'name': 'Mozambique', 'previous_rank': 99, 'points': 1234.04, 'previous_points': 1236.18, 'confederation': 'CAF'}, {'rank': 98, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/GUA', 'name': 'Guatemala', 'previous_rank': 100, 'points': 1230.73, 'previous_points': 1235.63, 'confederation': 'CONCACAF'}, {'rank': 99, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/PLE', 'name': 'Palestine', 'previous_rank': 98, 'points': 1230.55, 'previous_points': 1236.44, 'confederation': 'AFC'}, {'rank': 100, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/BLR', 'name': 'Belarus', 'previous_rank': 97, 'points': 1223.54, 'previous_points': 1237.24, 'confederation': 'UEFA'}, {'rank': 101, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/THA', 'name': 'Thailand', 'previous_rank': 102, 'points': 1222.2, 'previous_points': 1222.07, 'confederation': 'AFC'}, {'rank': 102, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/TRI', 'name': 'Trinidad and Tobago', 'previous_rank': 101, 'points': 1220.99, 'previous_points': 1229.11, 'confederation': 'CONCACAF'}, {'rank': 103, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/ARM', 'name': 'Armenia', 'previous_rank': 105, 'points': 1219.55, 'previous_points': 1204.78, 'confederation': 'UEFA'}, {'rank': 104, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/TJK', 'name': 'Tajikistan', 'previous_rank': 106, 'points': 1206.15, 'previous_points': 1202.54, 'confederation': 'AFC'}, {'rank': 105, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/COM', 'name': 'Comoros', 'previous_rank': 107, 'points': 1201.83, 'previous_points': 1198.51, 'confederation': 'CAF'}, {'rank': 106, 'flag': 'https://api.fifa.com/api/v3/picture/flags-sq-2/KGZ', 'name': 'Kyrgyz Republic', 'previous_rank': 104, 'points': 1

In [ ]:
## Data Cleaning and Export

We clean the dataset and keep only the necessary columns.
Then we export the dataset to a CSV file to be used in the package.

In [5]:
cols_to_keep = ['rank', 'name', 'points']
df_filtered = df[cols_to_keep]
print(df_filtered)

      rank                    name   points
0      1.0                   Spain  1875.37
1      2.0                  France  1870.92
2      3.0               Argentina  1870.32
3      4.0                 England  1820.44
4      5.0                Portugal  1779.55
..     ...                     ...      ...
206  207.0       US Virgin Islands   779.71
207  208.0  British Virgin Islands   768.50
208  209.0                Anguilla   758.52
209  210.0              San Marino   733.23
210    NaN                 Eritrea   855.56

[211 rows x 3 columns]

In [6]:
df_filtered['rank'] = pd.to_numeric(df_filtered['rank'])
df_filtered['points'] = pd.to_numeric(df_filtered['points'])
df_filtered["rank"] = df_filtered["rank"].astype("Int64")

print(df_filtered.head())

   rank       name   points
0     1      Spain  1875.37
1     2     France  1870.92
2     3  Argentina  1870.32
3     4    England  1820.44
4     5   Portugal  1779.55

In [ ]:
## Data Cleaning and Export

We clean the dataset and keep only the necessary columns.
Then we export the dataset to a CSV file to be used in the package.

In [7]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = file_path = "results.csv"

# Load the latest version
results_df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "martj42/international-football-results-from-1872-to-2017",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", results_df.head())

/Users/santiago/final_stats_386/final_project/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/var/folders/_y/ns92xnlj51d2sj00hr93x7r80000gn/T/ipykernel_8057/3667409590.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  results_df = kagglehub.load_dataset(

First 5 records:          date home_team away_team  home_score  away_score tournament     city  \
0  1872-11-30  Scotland   England         0.0         0.0   Friendly  Glasgow
1  1873-03-08   England  Scotland         4.0         2.0   Friendly   London
2  1874-03-07  Scotland   England         2.0         1.0   Friendly  Glasgow
3  1875-03-06   England  Scotland         2.0         2.0   Friendly   London
4  1876-03-04  Scotland   England         3.0         0.0   Friendly  Glasgow

    country  neutral
0  Scotland    False
1   England    False
2  Scotland    False
3   England    False
4  Scotland    False

In [8]:
df_filtered.to_csv('data/rankings.csv', index=False)

In [9]:
%pip install -e .

/Users/santiago/final_stats_386/final_project/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.

In [10]:
from wc_sim import calculate_weighted_rating
import pandas as pd

ranks  = pd.read_csv('data/rankings.csv')
titles = pd.read_csv('data/titles.csv')
df_weighted = calculate_weighted_rating(ranks, titles)

In [11]:
print(df_weighted.head(10))

   rank         name   points  wc_titles  weighted_rating
0     1    Argentina  1870.32          3          2020.32
1     2       Brazil  1761.60          5          2011.60
2     3       France  1870.92          2          1970.92
3     4        Spain  1875.37          1          1925.37
4     5        Italy  1710.06          4          1910.06
5     6      Germany  1704.27          4          1904.27
6     7      England  1820.44          1          1870.44
7     8     Portugal  1779.55          0          1779.55
8     9      Uruguay  1673.65          2          1773.65
9    10  Netherlands  1754.17          0          1754.17

In [12]:
from wc_sim import simulate_match

winner = simulate_match("Brazil", "Argentina", df_weighted)
print(winner)

Argentina

In [13]:
from wc_sim import simulate_match_n

simulate_match_n("Brazil", "Argentina", df_weighted, n=1000)

        team  wins  win_pct
0     Brazil   482     48.2
1  Argentina   518     51.8

In [14]:
from wc_sim import validate_weighted_rating

validate_weighted_rating(results_df, df_weighted)

            metric  correct_predictions  total_matches  accuracy_pct
0           points                20701          29668         69.78
1  weighted_rating                20795          29668         70.09